name: Cypress Tests

on:
  push:
    branches:
      - main  # Ou qualquer outra branch que você queira monitorar
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Executa o job no ambiente Ubuntu

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Versão do Node.js que você está usando

      - name: Install dependencies
        run: npm install  # Instala as dependências do projeto

      - name: Run Cypress tests
        run: npx cypress run
